Servlet Step 1 Done
SofiaPSU/sps-portfolio pull request #3
Opened 2021-03-05 06:01 UTC by SofiaPSU

I accidentally merged the work I did for step 1 onto main under the Sofia_Branch, so I created a new branch for week 2. Now I am trying to figure out how to undo that merge.

2021-03-05 17:49 UTC, GoogleyGabriel commented
> I accidentally merged the work I did for step 1 onto main under the Sofia_Branch, so I created a new branch for week 2. Now I am trying to figure out how to undo that merge.

Thats no biggie -- dw about unmerging.

2021-03-05 17:50 UTC, GoogleyGabriel requested changes
Make this PR only about changing the .xml files, note that in the description, and remove this file. Make this file be part of another PR where it is actually being used.

2021-03-07 15:19 UTC, claudiapao10 approved these changes

2021-03-07 15:19 UTC, claudiapao10 commented on portfolio/src/main/java/com/google/sps/servlets/NewServlet.java
> +@WebServlet("/step_one_servlet")
It is more descriptive, looks great!

2021-03-08 02:39 UTC, SofiaPSU commented
Removed the pom.xml files from this pull request

2021-03-10 07:31 UTC, GoogleyGabriel approved these changes

2021-03-10 07:31 UTC, GoogleyGabriel commented
Good job! Seems like you missed just one file -- but its not an issue. Keep up the good work

2021-03-12 06:49 UTC, merged